# Generated by Django 2.2.4 on 2019-11-26 23:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movimentacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, null=True)),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_movimentacao.movimentacao_set+', to='contenttypes.ContentType')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
        ),
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('movimentacao_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='movimentacao.Movimentacao')),
                ('fornecedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Fornecedor')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('movimentacao.movimentacao',),
        ),
        migrations.CreateModel(
            name='FluxoDeCaixa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_hora_abertura', models.DateTimeField()),
                ('data_hora_fechamento', models.DateTimeField(null=True)),
                ('valor_abertura', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('valor_em_fluxo', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('valor_final', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('movimentacoes', models.ManyToManyField(to='movimentacao.Movimentacao')),
            ],
        ),
        migrations.CreateModel(
            name='Estoque',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField(default=0)),
                ('data_validade', models.DateField(blank=True, null=True)),
                ('movimentacoes', models.ManyToManyField(to='movimentacao.Movimentacao')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Produto')),
            ],
        ),
        migrations.CreateModel(
            name='Agenda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Venda',
            fields=[
                ('movimentacao_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='movimentacao.Movimentacao')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Cliente')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('movimentacao.movimentacao',),
        ),
        migrations.CreateModel(
            name='OrdemServicoInterna',
            fields=[
                ('movimentacao_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='movimentacao.Movimentacao')),
                ('data_horario_inicial', models.DateTimeField()),
                ('data_horario_final', models.DateTimeField()),
                ('checkin', models.DateTimeField(blank=True, null=True)),
                ('checkout', models.DateTimeField(blank=True, null=True)),
                ('agenda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movimentacao.Agenda')),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Animal')),
                ('produtos', models.ManyToManyField(to='core.Produto')),
                ('servico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Servico')),
            ],
            options={
                'abstract': False,
            },
            bases=('movimentacao.movimentacao',),
        ),
        migrations.CreateModel(
            name='OrdemServicoExterna',
            fields=[
                ('movimentacao_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='movimentacao.Movimentacao')),
                ('data_horario_inicial', models.DateTimeField()),
                ('data_horario_final', models.DateTimeField()),
                ('agenda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movimentacao.Agenda')),
                ('animals', models.ManyToManyField(to='core.Animal')),
                ('servico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Servico')),
            ],
            options={
                'abstract': False,
            },
            bases=('movimentacao.movimentacao',),
        ),
        migrations.CreateModel(
            name='ItemDeVenda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.DecimalField(decimal_places=2, max_digits=5)),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=5)),
                ('produto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Produto')),
                ('venda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movimentacao.Venda')),
            ],
        ),
        migrations.CreateModel(
            name='ItemDeCompra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.DecimalField(decimal_places=2, max_digits=10)),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('produto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Produto')),
                ('compra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movimentacao.Compra')),
            ],
        ),
    ]
